name: Android Release CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Get LTW
        uses: dawidd6/action-download-artifact@v7
        continue-on-error: true
        with:
          github_token: ${{secrets.LTW_CLONER_SECRET}}
          repo: PojavLauncherTeam/BigTinyWrapper
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs
          allow_forks: false

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-new
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-pojav

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-21
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-pojav

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11"

      - name: Build JRE JAR files
        run: |
          ./scripts/languagelist_updater.sh

          mkdir out
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release .apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleRelease
          mv app_pojavlauncher/build/outputs/apk/release/app_pojavlauncher-release.apk out/app-release.apk

      - name: Undo Commit If Build Fails
        if: ${{ github.event_name == 'push' && failure() }}
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          git reset --hard HEAD~1
          git push --force-with-lease

      - name: Gen md5sum
        run: |
          md5sum out/app-release.apk > out/app-release.md5

      - name: Upload APK
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: out/app-release.*